server_directory = "server"
port = 8080
timeout = 30
max_connections = 1000
bind_address = "0.0.0.0"
cache_enabled = true
default_max_age = 86400
development_mode = false
enable_compression = true
min_size_to_compress = 1024
static_root = "static"
max_file_size = 10485760
js_minify = true
js_root_dir = "static/js"
enable_websockets = false
websocket_path = "/ws"
websocket_max_connections = 1000
websocket_timeout = 60
custom_error_pages = false
php_enabled = true
php_cgi_path = "php/php-cgi.exe"
php_exe_path = "php/php.exe"
php_root_dir = "web"
php_timeout = 30

[file_extension_cache_times]
gif = 31536000
ico = 31536000
css = 604800
js = 604800
woff2 = 2592000
jpeg = 31536000
otf = 2592000
webp = 31536000
woff = 2592000
eot = 2592000
jpg = 31536000
ttf = 2592000
html = 3600
htm = 3600
png = 31536000
svg = 31536000

[error_pages]
402 = "errors/402.html"
504 = "errors/504.html"
409 = "errors/409.html"
408 = "errors/408.html"
413 = "errors/413.html"
415 = "errors/415.html"
426 = "errors/426.html"
431 = "errors/431.html"
424 = "errors/424.html"
401 = "errors/401.html"
503 = "errors/503.html"
510 = "errors/510.html"
411 = "errors/411.html"
511 = "errors/511.html"
429 = "errors/429.html"
417 = "errors/417.html"
502 = "errors/502.html"
428 = "errors/428.html"
404 = "errors/404.html"
421 = "errors/421.html"
414 = "errors/414.html"
410 = "errors/410.html"
500 = "errors/500.html"
501 = "errors/501.html"
425 = "errors/425.html"
507 = "errors/507.html"
422 = "errors/422.html"
505 = "errors/505.html"
508 = "errors/508.html"
407 = "errors/407.html"
405 = "errors/405.html"
418 = "errors/418.html"
403 = "errors/403.html"
506 = "errors/506.html"
423 = "errors/423.html"
451 = "errors/451.html"
412 = "errors/412.html"
416 = "errors/416.html"
400 = "errors/400.html"
406 = "errors/406.html"
